spring:
#  data:
#    elasticsearch:
#      client:
#        reactive:
#          endpoints: http://192.168.3.3:9200
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql@123A
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.3.3:3306/es?characterEncoding=utf8&serverTimezone=UTC
    #    ?allowMultiQueries=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
    validationQuery: select 'x'
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    filters: stat,wall,slf4j
    initialSize: 1
    maxActive: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 30000
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 3
  elasticsearch:
    rest:
      uris: http://192.168.3.3:9200
logging:
  level:
    mybatis: debug
#mapper:
#  identity: MYSQL
#  mappers: com.seesea.job.common.BaseMapper
#  not-empty: false
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.seesea.job.entity
server:
  port: 8000










